# Generated by Django 4.2.17 on 2025-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_url", models.URLField()),
                ("target_id", models.CharField(max_length=50)),
                ("scan_id", models.CharField(max_length=50)),
                ("low_vulns", models.PositiveIntegerField(default=0)),
                ("info_vulns", models.PositiveIntegerField(default=0)),
                ("medium_vulns", models.PositiveIntegerField(default=0)),
                ("high_vulns", models.PositiveIntegerField(default=0)),
                ("total_vulns", models.PositiveIntegerField(default=0)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("task_status", models.CharField(max_length=50)),
                ("scan_mode", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
