# Generated by Django 4.2 on 2023-04-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='info_vulns',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
