# Generated by Django 4.2 on 2023-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0002_scanresult_info_vulns'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='scan_mode',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
