# Generated by Django 4.2 on 2023-04-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0004_alter_scanresult_scan_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='scan_mode',
        ),
    ]
