# Generated by Django 4.2 on 2023-04-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0009_alter_scanresult_scan_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='scan_mode',
            field=models.IntegerField(),
        ),
    ]
