# Generated by Django 4.2 on 2023-04-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulscan', '0010_alter_scanresult_scan_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanresult',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
