# Generated by Django 4.2.17 on 2025-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=128)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
