# Generated by Django 4.2.17 on 2025-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_url", models.URLField(max_length=255)),
                ("scan_path", models.CharField(max_length=255)),
                ("response_code", models.PositiveSmallIntegerField()),
                ("access_status", models.CharField(max_length=20)),
                ("scan_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
