# Generated by Django 4.2 on 2023-04-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.PositiveIntegerField(unique=True)),
                ('service', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
