# Generated by Django 3.1.4 on 2023-04-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.PositiveIntegerField(unique=True)),
                ('service', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=10)),
            ],
        ),
    ]
