# Generated by Django 4.2.17 on 2025-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article_info",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_href", models.CharField(max_length=100)),
                ("article_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
                ("author_name", models.CharField(max_length=100)),
                ("author_image_url", models.URLField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="CWE_INFO",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cwe_ranking", models.PositiveIntegerField()),
                ("cwe_id", models.CharField(max_length=50)),
                ("cwe_name", models.CharField(max_length=255)),
                ("cwe_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("cwe_comparison", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
