# Generated by Django 3.1.4 on 2023-04-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
