# Generated by Django 4.2 on 2023-04-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0002_scanresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.DeleteModel(
            name='ScanResult',
        ),
    ]
