# Generated by Django 4.2 on 2023-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webscan', '0003_delete_port_delete_scanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWE_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwe_ranking', models.PositiveIntegerField()),
                ('cwe_id', models.CharField(max_length=50)),
                ('cwe_name', models.CharField(max_length=255)),
                ('cwe_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cwe_comparison', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
